### ISSUE TITLE
Preact Typescript incompatibility

### ISSUE THREAD

**Issue by dephiros** [tailwindlabs/tailwindui-react#10]
I am trying to use the `Transition` component with Preact Typescript(preach-cli with typescript template) and receive this error:

```
'Transition' cannot be used as a JSX component.
  Its return type 'JSX.Element' is not a valid JSX element.
    Type 'Element' is missing the following properties from type 'Element': nodeName, attributes, childrents(2786)
```

Appreciate help to resolve this

**Comment by RobinMalfait** [comment]
Hey @dephiros could you provide a repro case (maybe a https://codesandbox.io/)?

**Comment by dephiros** [comment]
Hi @RobinMalfait , thank you for the quick response.
I cannot quickly create a codesandbox but created a small git repo: https://github.com/dephiros/preact-typescript-tailwind

In this repo, if you go to `src/components/nav` using vscode, you will see the error on the `Transition` component usage

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
