### ISSUE TITLE
Is this project receptive to PRs at this point? 

### ISSUE THREAD

**Issue by HerbCaudill** [tailwindlabs/tailwindui-react#13]
Hi - I recently purchased Tailwind UI for use in a React project, and I'm in the process of turning some of the elements I need into components. Are you open to contributions?

**Comment by trevyn** [comment]
I agree that there needs to be a story better than the status quo for fully React-ified, fully-classed-up Tailwind UI components, whether that’s first-party or community-led.

**Comment by RobinMalfait** [comment]
Hello!

Thank you for your interest! Currently we don't accept/allow contributions for new components just yet, maybe in a later phase. That being said, this library is **not** a library for the Tailwind UI components itself. So we will not create visual `Button`, `Form`, `Modal`, `Alert`, `Navbar`, ... components in this repo. It is a library of headless components that will help you to create accessible applications. The components don't have anything "Tailwind UI" specific built-in.

Let me know if you have further questions!

**Comment by HerbCaudill** [comment]
Ah - got it. That makes sense; I'd misunderstood the purpose of this project. 

Out of curiosity, are there any plans for a (subscribers-only) React implementation of Tailwind UI?
