### ISSUE TITLE
Transitioning happening without state change

### ISSUE THREAD

**Issue by cgcullen** [tailwindlabs/tailwindui-react#14]
I was using this version of the React Transition with a slide in/out sidebar: https://gist.github.com/adamwathan/3b9f3ad1a285a2d1b482769aeb862467

I switched it out for this tailwindui-react package, but now the transition happens with each page change (I'm using Next.js).

    <Transition
      show={isOpen}
      enter="transition ease-in-out duration-500 sm:duration-700 transform"
      enterFrom="-translate-x-full"
      enterTo="translate-x-0"
      leave="transition ease-in-out duration-500 sm:duration-700 transform"
      leaveFrom="translate-x-0"
      leaveTo="-translate-x-full"
    >

With the old gist code, my sidebar stayed open until I set the state to false, even on page changes.

With this new package, my state doesn't change, but each time I go to another page, the transition happens as if I've closed and then opened.

I'm using the same code for each, only changing the import from 'components/Transition' to '@tailwind-ui/react

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
