### ISSUE TITLE
Transition.Child is shrinking mobile sidebar

### ISSUE THREAD

**Issue by dan-kwiat** [tailwindlabs/tailwindui-react#2]
Something weird is going on when I implement the [first sidebar layout](https://tailwindui.com/components/application-ui/application-shells/sidebar#component-17f40014d95a5c5bb5628b9d69558a69) with this transition library.

- The transitions are fine but the off-canvas menu gets reduced to 175px width, and isn't full height either. Without the second `Transition.Child` it renders at the expected size.
- The problem occurs regardless of whether props are passed to the second `Transition.Child`.
- I have included `layout: "sidebar"` in my config.

On a side note - did you update the docs to point to this package instead of Adam's gist in the few hours since I first read the docs?! Last update says Aug 19 and I'm very confused.

```jsx
import { useState } from "react"
import { Transition } from "@tailwindui/react"

export default function AppLayout({ children }) {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  return (
    <div className="h-screen flex overflow-hidden bg-gray-100">
      {/* <!-- Off-canvas menu for mobile --> */}
      <Transition show={isMobileMenuOpen}>
        <div className="md:hidden">
          <div className="fixed inset-0 flex z-40">
            <Transition.Child
              enter="transition-opacity ease-linear duration-300"
              enterFrom="opacity-0"
              enterTo="opacity-100"
              leave="transition-opacity ease-linear duration-300"
              leaveFrom="opacity-100"
              leaveTo="opacity-0"
            >
              <div className="fixed inset-0">...</div>
            </Transition.Child>

            <Transition.Child
              enter="transition ease-in-out duration-300 transform"
              enterFrom="-translate-x-full"
              enterTo="translate-x-0"
              leave="transition ease-in-out duration-300 transform"
              leaveFrom="translate-x-0"
              leaveTo="-translate-x-full"
            >
              <div
                className="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-indigo-800"
              >
                ...
              </div>
            </Transition.Child>
            <div className="flex-shrink-0 w-14">
              {/* <!-- Dummy element to force sidebar to shrink to fit close icon --> */}
            </div>
          </div>
        </div>
      </Transition>

      {/* <!-- Static sidebar for desktop --> */}
      <div className="hidden md:flex md:flex-shrink-0">...</div>
      
      <div className="flex flex-col w-0 flex-1 overflow-hidden">...</div>
    </div>
  )
}
```

**Comment by dan-kwiat** [comment]
Sorry, I didn't realise `Transition` and `Transition.Child` render a div - I thought they were just modifying their children.  The answer is to include the class names on the Transition components, not their children.

**Comment by adamwathan** [comment]
Hey! Yep we silently released this today so you are one of the very first people to try it 👀

Another option is to use a render prop for the child so you don't get the extra div 👍🏻 covered in the README but on my phone so hard to get you a link.

**Comment by dan-kwiat** [comment]
Cool thanks. Btw the react transition example here is making the same mistake as me:
https://tailwindui.com/documentation#js-react

I'll open an issue on the tailwindui-issues repo
