### ISSUE TITLE
TypeError: React.createContext is not a function

### ISSUE THREAD

**Issue by jan-wilhelm** [tailwindlabs/tailwindui-react#5]
Hey, thanks for this awesome project!

I was super excited to start using it and then I ran into this problem that, to me, seems to be caused by tailwindui-react.

I am using NextJS with TypeScript and Jest for testing, all dependencies are on their `@latest` versions.

When I have a Jest test in which I import my custom `Dropdown` component that imports `import { Transition } from '@tailwindui/react';` , Jest fails with 
```
TypeError: React.createContext is not a function

    > 1 | import { Transition } from '@tailwindui/react';
        | ^
```

I have tried the [common possible solutions to this](https://stackoverflow.com/questions/54302725/react-createcontext-is-not-a-function-but-i-am-not-using-it) (i.e. making sure that react and react-dom are up to date) but this does not seem to have any effect. I have also already run `rm -rf node_modules && yarn`.

Do you have any idea how to solve this and is it really an issue with this library or am I doing something wrong? I have dozens of other tests that also import some other libraries (some of which also internally use `React.createContext` but which never make my tests fail).

Setup: NextJS with Typescript, Jest with `ts-jest`, React 16.13. Everything is up to date

**Comment by RobinMalfait** [comment]
Hello! Is it possible to create a reproduction repo / codesandbox for this?
I created a very basic Next.js application and the build seems to work correctly here:
![image](https://user-images.githubusercontent.com/1834413/91501362-c5071b00-e8c5-11ea-8f0f-a59ff39d9027.png)

> Alt text: screenshot of my editor where on the left is a `package.json` file with the latest `react` and `@tailwindui/react` version. On the right is an example React component where the `@tailwindui/react` component is used. On the bottom is a terminal showing the output of a successful `next build` command.

**Comment by tlttnz2018** [comment]
@jan-wilhelm 

You need to import React even though there is no React component, I guess

**Comment by RobinMalfait** [comment]
@tlttnz2018 That's true, however they are using `Next.js` so that should not be necessary. When I just have that `import { Transition } from "@tailwindui/react";` it still works 🤔

**Comment by qw-in** [comment]
I would hazard a guess that the issue may be with jest or ts-jest rather than next.js

**Comment by jan-wilhelm** [comment]
@RobinMalfait yes, I will try to set up a repo in a couple days, when I have time

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
