### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by dotamir** [tailwindlabs/tailwindui-react#8]
Hi there. I hope you'd be alright.
I'm looking for have a contribution here and I really got interested in it. I didn't see any contribution guide and if you accept any help from me, I'd be happy to help you develop it.

Thanks in advance.

**Comment by RobinMalfait** [comment]
Hey, thanks for reaching out!

Currently we don't have any contribution guides since we are still developing the initial versions of everything. Once our components mature a bit more and get used more, then we will look into adding these guides if necessary. But for now, we don't have them yet.
